apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service
  namespace: payments
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payments-service
      harness.io/track: stable
  template:
    metadata:
      labels:
        app: payments-service
        harness.io/track: stable
    spec:
      containers:
        - name: payments-service
          image: pavantechy09hub/payments-service:latest
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
